pool:
  name: 'default'

steps:

- task: revbits-azure-devops@0
  inputs:
    pamhostname: 'https://staging.enpast.com'
    apikey: 'da6cca92a78e4011ac0e404e17a26257f086acbd3de5de7abd8bc0a0f6a41fcad33eea0c048abfbf6fe6ff6f291c2105cd822077b2ac624c393415cecb39fc81'
    pamsecretkeys: '12345abc'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(pamsecretkeys)"
    echo "$(pamsecretkeys)" | sed 's/./& /g'