pool:
  name: 'default'

steps:

- task: revbits-azure-devops@0
  inputs:
    pamhostname: 'https://staging.enpast.com'
    apikey: 'e0216ad84bb34d5ce13455ab2b2106b41ef56b0004279776d9cc2ee28bba57f0f1836a598d56e1e658ac0fdcd3a9348becde8eeb89a45f248e2552f14317b3a2'
    pamsecretkeys: 'dockerhub'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(dockerhub)"
    echo "$(dockerhub)" | sed 's/./& /g'