pool:
  vmImage: 'ubuntu-latest'

steps:

- task: revbits-azure-devops@0
  inputs:
    pamhostname: 'https://pv.revbits.net'
    apikey: 'asdasd'
    pamsecretkeys: 'test'

- bash: |
    echo "Secrets retrieved:"
    echo "  SECRET1: $(pamsecretkeys)"
    echo "$(pamsecretkeys)" | sed 's/./& /g'